services:
  db:
    image: postgres:15
    container_name: user_db
    restart: always
    environment:
      POSTGRES_DB: fitness_user_db
      POSTGRES_USER: parulsachan86
      POSTGRES_PASSWORD: Avengers@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: activityservice-db
    restart: always
    ports:
      - "27017:27017"
    # Note: If .env is missing, Docker will throw an error.
    # Ensure MONGO_USERNAME and MONGO_PASSWORD are defined there.
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: