spring.application.name=activityservice

server.port=8081
#mongodb://localhost:27017/
# MongoDB Connection
spring.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/activity_database?authSource=admin

# Optional: Show queries in logs for debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG